In [1]:
import numpy as np

Declaring matrices

In [2]:
mx1 = np.array([[5, 10], [15, 20]])
mx2 = np.array([[25, 30], [35, 40]])

print("Matrix1 =\n",mx1)
print("\nMatrix2 =\n",mx2)

Matrix1 =
 [[ 5 10]
 [15 20]]

Matrix2 =
 [[25 30]
 [35 40]]


Addition using Numpy methods

In [3]:
print ("\nAddition of two matrices: ")
print (np.add(mx1,mx2))


Addition of two matrices: 
[[30 40]
 [50 60]]


Subtraction using Numpy methods

In [5]:
print ("\nSubtraction of two matrices: ")
print (np.subtract(mx1,mx2))


Subtraction of two matrices: 
[[-20 -20]
 [-20 -20]]


Division using Numpy methods

In [6]:
print ("\nMatrix Division: ")
print (np.divide(mx1,mx2))


Matrix Division: 
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


Multiplication using Numpy methods

In [8]:
print ("\nMultiplication of two matrices: ")
print (np.multiply(mx1,mx2))


Multiplication of two matrices: 
[[125 300]
 [525 800]]


<h4>Optimized methods of multiplication</h4>

In [9]:
mx1 @ mx2

array([[ 475,  550],
       [1075, 1250]])

In [10]:
np.matmul (mx1, mx2)

array([[ 475,  550],
       [1075, 1250]])

In [11]:
np.dot (mx1, mx2)

array([[ 475,  550],
       [1075, 1250]])

<h4>Summation of Matrix</h4>

In [14]:
mx = np.array([[5, 10], [15, 20]])

print("Matrix =\n",mx)

print ("\nThe summation of elements=")
print (np.sum(mx))

print ("\nThe column wise summation=")
print (np.sum(mx,axis=0))

print ("\nThe row wise summation=")
print (np.sum(mx,axis=1))

Matrix =
 [[ 5 10]
 [15 20]]

The summation of elements=
50

The column wise summation=
[20 30]

The row wise summation=
[15 35]


<h4>Transpose of Matrix</h4>

In [15]:
mx = np.array([[5, 10], [15, 20]])

print("Matrix =\n",mx)

print ("\nThe Transpose =")
print (mx.T)

Matrix =
 [[ 5 10]
 [15 20]]

The Transpose =
[[ 5 15]
 [10 20]]


#### Numpy method is also available

In [16]:
np.transpose (mx)

array([[ 5, 15],
       [10, 20]])

#### Inverse of a matrix

In [17]:
np.linalg.inv (mx)

array([[-0.4,  0.2],
       [ 0.3, -0.1]])